version: '3.8'

services:
  arch_builder:
    image: ghcr.io/zhulik/arch_builder:latest
    volumes:
      - ./cache/pkg:/var/cache/pacman/pkg
      - ./cache/pikaur:/home/user/.cache/pikaur/pkg
      - ./cache/go:/home/user/go
      - /tmp:/tmp
