---
name: Build

on: [push, pull_request]

jobs:
  linting:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
          format: 'YYYY.MM.DD'
      - name: Build container
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u USERNAME --password-stdin
          docker build -t "ghcr.io/zhulik/arch_builder" .
          docker tag "ghcr.io/zhulik/arch_builder" "ghcr.io/zhulik/arch_builder:$TIME"
          docker push "ghcr.io/zhulik/arch_builder:latest"
          docker push "ghcr.io/zhulik/arch_builder:$TIME"
