---
name: Build

on: [push, pull_request]

jobs:
  linting:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from GitHub
        uses: actions/checkout@v2
      # - uses: actions/cache@v2
      #   with:
      #     path: ~/.cache/pip
      #     key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      - name: Build container
        run: docker-compose build
      - name: Build some package
        run: docker-compose run arch_builder build.rb adguardhome
